image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - yarn install
            - yarn deploy
