image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
            - firebase-hosting
          script:
            - yarn install
            - yarn deploy-content

definitions:
  caches:
    firebase-hosting: .firebase
