import Vue from 'vue';
import Vuetify, {
  VApp,
  VAvatar,
  VBtn,
  VCheckbox,
  VDivider,
  VExpansionPanel,
  VExpansionPanelContent,
  VFlex,
  VIcon,
  VLayout,
  VList,
  VListGroup,
  VListTile,
  VListTileAction,
  VListTileAvatar,
  VListTileContent,
  VListTileTitle,
  VListTileSubTitle,
  VRangeSlider,
  VSelect,
  VSpacer,
  VSubheader,
} from 'vuetify/lib';

Vue.use(Vuetify, {
  components: {
    VApp,
    VAvatar,
    VBtn,
    VCheckbox,
    VDivider,
    VExpansionPanel,
    VExpansionPanelContent,
    VFlex,
    VIcon,
    VLayout,
    VList,
    VListGroup,
    VListTile,
    VListTileAction,
    VListTileAvatar,
    VListTileContent,
    VListTileTitle,
    VListTileSubTitle,
    VRangeSlider,
    VSelect,
    VSpacer,
    VSubheader,
  },
});
